### ISSUE TITLE
Fails right after start?

### ISSUE THREAD

**Issue by remv** [TheRemote/MinecraftBedrockServer#10]
Hi! 
I just tried to setup this server on a Ubuntu 18.04.03. Right after the install finished it gives me this: 
`Server is already started!  Press screen -r minecraft to open it`

But I cannot jump into the screen:
`minecraft@minecraft:~/minecraftbe/minecraft$ screen -r minecraft`
`There is no screen to be resumed matching minecraft.`

Also tried running it manually, but im not getting any errors:
`minecraft@minecraft:~/minecraftbe/minecraft$ ./start.sh`
`Server is already started!  Press screen -r minecraft to open it`

`minecraft@minecraft:~/minecraftbe/minecraft$ screen -r minecraft`
`There is no screen to be resumed matching minecraft.`

Any ideas?

**Comment by remv** [comment]
This might also be helpful:

minecraft@minecraft:~/minecraftbe/minecraft$ systemctl status minecraft.service
● minecraft.service - minecraft minecraft server
   Loaded: loaded (/etc/systemd/system/minecraft.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-08-25 20:02:08 UTC; 27min ago
  Process: 1713 ExecStart=/bin/bash /home/minecraft/minecraftbe/minecraft/start.sh (code=exited, status=1/FAILURE)

Aug 25 20:02:08 minecraft systemd[1]: Starting minecraft minecraft server...
Aug 25 20:02:08 minecraft bash[1713]: Server is already started!  Press screen -r minecraft to open it
Aug 25 20:02:08 minecraft systemd[1]: minecraft.service: Control process exited, code=exited status=1
Aug 25 20:02:08 minecraft systemd[1]: minecraft.service: Failed with result 'exit-code'.
Aug 25 20:02:08 minecraft systemd[1]: Failed to start minecraft minecraft server.

**Comment by TheRemote** [comment]
Hey remv,

It is saying there is already a copy of the server running.  Can you type screen -r and see which screen sessions are already open?

**Comment by remv** [comment]
Thats the wierd thing. There is nothing running at all!

One curiosity though. My first try I named the server "minecraft" when the script asked. I just tried running the SetupMinecraft.sh script again and choose another name, that seemed to to work:

NO LOG FILE! - setting up server logging...
[2019-08-25 20:42:53 INFO] Starting Server
[2019-08-25 20:42:53 INFO] Version 1.12.0.28
[2019-08-25 20:42:53 INFO] Session ID 58790c3a-3072-449c-9fe8-d5db169cef22
[2019-08-25 20:42:53 INFO] Level Name: Bedrock level
[2019-08-25 20:42:53 INFO] Game mode: 1 Creative
[2019-08-25 20:42:53 INFO] Difficulty: 1 EASY
[2019-08-25 20:42:55 INFO] IPv4 supported, port: 19132
[2019-08-25 20:42:55 INFO] IPv6 supported, port: 19133
[2019-08-25 20:42:55 INFO] IPv4 supported, port: 56426
[2019-08-25 20:42:55 INFO] IPv6 supported, port: 56072
[2019-08-25 20:42:57 INFO] Server started.

But im still not able to connect to it. Hmm

**Comment by TheRemote** [comment]
Okay that's a pretty interesting bug you found haha.

This is looking much better but I'm not sure why it is listening on 2 interfaces.  It looks like it's listening on 19132 and 56426?  Try giving 56426 a connect

**Comment by remv** [comment]
haha. Okey: So I tried some things now. First, I found out that my server was set to the wrong timezone, corrected it and did a reboot. After some mins the server was up and running and I got connected! hehe. Thank you so much for a GREAT tool! My kids will be trilled!

Btw. Maybe put something in the script so other people don`t name their server "minecraft" - that won`t work :D

**Comment by TheRemote** [comment]
I'm glad you got it working!  I'll definitely fix the Minecraft name bug for sure :)
