### ISSUE TITLE
Unable to connect to world from outside network, even though TCP and UDP port forwarding working

### ISSUE THREAD

**Issue by ryanerwin** [TheRemote/MinecraftBedrockServer#101]
Is there anything inside of the minecraft bedrock server that maintains a list of allowed IP addresses?

When I try to connect to my minecraft bedrock server from outside of my network, I get:

![image](https://user-images.githubusercontent.com/2156415/127675982-d6864ee4-f124-472b-9798-8e862e8d6347.png)

However, I'm able to connect just fine from outside my network to both TCP and UDP port `19132`...

To verify that TCP port forwarding was working, I configured SSHD to also listen on port `19132` and connected, works fine, so I reset SSHD's listening ports to get it out of the way.

To verify that UDP port forwarding was working, on my minecraft server box I ran:

```
nc -luk 0.0.0.0 19132
```

Then from my Android device that runs my minecraft client, while connected over the mobile network, in Termux I ran:

```
echo "HELLO FROM PHONE" | ncat -uv MY.HOME.IP 19132
Ncat: Version 7.91 ( https://nmap.org/ncat )
Ncat: Connected to MY.HOME.IP:19132.
Ncat: 17 bytes sent, 0 bytes received in 0.03 seconds.
```

On my minecraft server box, sure enough I saw:

```
 ~  nc -luk 0.0.0.0 19132
HELLO FROM PHONE
```

So I'm 100% sure TCP and UDP port forwarding are working properly for port `19132`.

My `bedrock_server` is listening on UDP just fine:

```
~  sudo ss -4lnp | grep -i bedrock
udp   UNCONN 0      0              0.0.0.0:19132      0.0.0.0:*    users:(("bedrock_server",pid=3222511,fd=7))
udp   UNCONN 0      0              0.0.0.0:39537      0.0.0.0:*    users:(("bedrock_server",pid=3222511,fd=9))
```

Yet every time I try to connect to my minecraft server via the remote network, I get:

![image](https://user-images.githubusercontent.com/2156415/127677053-9abc4364-ef6b-4545-bf78-74dfc90fa749.png)

![image](https://user-images.githubusercontent.com/2156415/127677077-1c894629-e14a-4705-aa76-d08e4a8927b0.png)

However, if I connect to WiFi and try to connect over my local network, the "Current Ping" shows up and I can connect just fine.

![image](https://user-images.githubusercontent.com/2156415/127677247-94536b8e-b054-41bc-83b3-d35df82e564e.png)

Besides port forwarding on the router, firewall rules on the host (which should both be covered by my `nc/ncat/netcat` tests, what else could be preventing me from getting a good Minecraft Bedrock Server connection across the Internet, yet the local connection works fine.

**Comment by TheRemote** [comment]
It's likely the default ports BDS bug mentioned in the README.  Try setting your ports to anything except the default ports and your "ping" status should show up green again.

When the server starts you'll notice it will say it's listening on 4 different ports including the default ports + the ports you used.  This is all buggy stuff that has been in for years but that seems to be the workaround.

It doesn't have anything to do with these scripts / this project.  This would be the official Bedrock server.  You can see this bug and all the bugs at https://bugs.mojang.com/projects/BDS/issues/BDS-14212?filter=allopenissues
