### ISSUE TITLE
Autostart not working when using separate data disk

### ISSUE THREAD

**Issue by tobimax** [TheRemote/MinecraftBedrockServer#102]
Hi,

Running on Ubuntu 20.4 in Azure, the Auto Start is just not working. I installed into a separate disk (/datadrive) I can start the server manually but it just when using the service start it fails.

sudo systemctl start thedatacrew

A dependency job for thedatacrew.service failed. See 'journalctl -xe' for details.

And the dependency is the datadrive.mount 

although the /datadrive is automounted via fstab

any ideas how to get this working on a separate drive?

thanks

toby.

**Comment by TheRemote** [comment]
Hey tobimax,

What does journalctl -xe say?

The script doesn't actually have any dependencies.  The only thing it "depends" on would be:
`WantedBy=multi-user.target`

This system does not appear to be functioning normally.  That is actually just a normal system run state and not a "dependency" like something installed.

Can you post your journalctl -xe?

**Comment by TheRemote** [comment]
Guessing that this was solved here as something with the automount or something that was likely very clear when checking journalctl -xe.  Definitely feel free to reopen if this isn't the case!
