### ISSUE TITLE
systemd minecraft service failure

### ISSUE THREAD

**Issue by stxdigitizing** [TheRemote/MinecraftBedrockServer#105]
I have been using this script for a while now. works great every time until something unknown happens. This isn't the first time I've had issues with starting the minecraft server. usually when the SYSTEMD fails I can manually start the server using the ./bedrock_server command. but this time didn't work... I receive this error when starting the service.

`Aug 27 14:02:28 minecraftrm bash[1677]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Aug 27 14:02:28 minecraftrm bash[1677]:                                  Dload  Upload   Total   Spent    Left  Speed
Aug 27 14:02:28 minecraftrm bash[1677]: [237B blob data]
Aug 27 14:02:28 minecraftrm bash[1677]: Minecraft Bedrock server is up to date...
Aug 27 14:02:28 minecraftrm bash[1677]: Starting Minecraft server.  To view window type screen -r Realm
Aug 27 14:02:28 minecraftrm bash[1677]: To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
Aug 27 14:02:28 minecraftrm systemd[1]: Started Realm Minecraft Bedrock Server.
Aug 27 14:02:28 minecraftrm bash[1737]: Server is not currently running!
Aug 27 14:02:28 minecraftrm systemd[1]: Realm.service: Control process exited, code=exited status=1
Aug 27 14:02:28 minecraftrm systemd[1]: Realm.service: Failed with result 'exit-code'.
`
I do not see any other errors... 

I have already deleted all instances of the server and did a fresh install but does the same thing...

any thoughts?

**Comment by TheRemote** [comment]
Ugh, I'm sorry that didn't lead to a better outcome!  Thanks for posting the resolution and for bearing with me.  These are pretty hard to troubleshoot sometimes.  Take care!

**Comment by stxdigitizing** [comment]
no it's good, with out problems arising you don't learn... what I learned now is to make a script that takes the backup folder and pushes it to an folder on my NAS and some how set args to warn if any of the important file have zero kilobytes before it overwrites. not sure if it's possible but going to give it a go.

I appreciate your help!

**Comment by stxdigitizing** [comment]
found this on Reddit and i was able to fix my world.

Minecraft Bedrock

The steps to recover a save on the bedrock edition are surprisingly similar to those shown in the video. They are different, however. Using the video I figured out how to recover a world in the bedrock edition after my own world became corrupted. Here are the steps:

Step 1: Same as java edition. Identify the problem.

If your problem is the same as the one in my example you may need to set your difficulty to peaceful before loading the fixed save, as it may crash again.

Step 2: Create a new world.

Again the same as java edition. This creates new, uncorrupted files that we need to repair the old world.

Step 3: Open your worlds directory.

This directory is a tough one to find. And a long one at that. Too long for me to type on mobile, so Here is a link to an answer on stack exchange on how to reach the directory.

Step 4: Find your new world folder.

After opening your minecraftworlds folder you should see files with names like "1g4AAHBsAQA=". These are your worlds. You can tell what world is what by opening the file and opening levelname.txt.

Step 5: Copy the new Level.dat and Level.dat_old files. Note that level.dat may display as only level in the world folder

Step 6: Go to the corrupt world and replace the two corrupt level.dat files with the two new ones.

This will fix your save and make it playable once again. You won't spawn in some random spot like in java edition and you will keep all of your items.

I hope this guide was able to help you fix your corrupt saves. And thanks to YouTuber KaysPlays for creating an amazing guide to help me recover my own world.

Have fun and enjoy playing on your worlds!
