### ISSUE TITLE
multiple server port issues

### ISSUE THREAD

**Issue by marcb1387** [TheRemote/MinecraftBedrockServer#106]
When running multiple servers I needed to stagger the cron auto reboot since my second server was taking the port of my first server causing the first to crash on start up.

**Comment by da99Beast** [comment]
Under your minecraft user account you should be able to view/modify your crontab by using the "crontab -e" command.

Here is a link to explain the format for the schedule. 

https://help.ubuntu.com/community/CronHowto

**Comment by TheRemote** [comment]
Your servers are on the same ports?  How?  That doesn't make sense, and why would you want them to be?

The port is like putting someone's name on an envelope.  If you don't put a name on the envelope it would just be delivered to the address but not addressed to a person.  Having two servers on the same port would be like having two people living in the same house with the same name.  

This is a misconfiguration.  Your servers should have different IPV4 and different IPV6 ports for each server.  They should never overlap like this.

Probably will not be making any changes for this one.  If I do it will be to make it check to make sure you aren't trying to do this and not allow you to have duplicate ports!

**Comment by marcb1387** [comment]
My servers do have different ports ipv4 and ipv6. the issue is when they both try and start at the same time. 

in the logs they show 2 sets of ports 

[2021-09-25 04:00:42] [INFO] IPv4 supported, port: 19132 - ports set in server.properties
[2021-09-25 04:00:42] [INFO] IPv6 supported, port: 19133 - ports set in server.properties
[2021-09-25 04:00:42] [INFO] Server started.
[2021-09-25 04:00:42] [INFO] IPv4 supported, port: 33104
[2021-09-25 04:00:42] [INFO] IPv6 supported, port: 42095

this second set is where I have trouble. when both servers reboot at the same time it will for some unknow reason to me start with my first servers ports unless I stagger the reboot times. now if the script would stagger them already it would eliminate issues occurring in the future for others. 

in the end im just trying to help prevent issues in the future if this is too much thats fine i was able to work around the problem by stagger my cron reboots of each server by 5 min.

**Comment by TheRemote** [comment]
Hey marc,

Thanks for clarifying, that is really not what I got from your first post but I did suspect this might have been what you were talking about.  Don't be too offended by my original reply as I wrote that with the intention of leaving this information for others who were trying to actually run the server on the same ports.  I hadn't really documented that anywhere so I took the chance to write it down if anyone is searching issues for them to find.

I think I can help with this additional information.  The issue can usually be eliminated by not using the default ports on *any* of your servers (19132, 19133).  That is the ones that are overlapping.  It's a bug.  It's been in for years and at this point I'm certain it will never be fixed (it has been like 2-3 years and dozens of major versions).  I think they will continue to move in the paid "Realms" cloud server direction and continue to give the dedicated servers the shaft.

You only have to start the servers in a certain order if you are using the default ports on one of them.  Here's some references:

https://github.com/TheRemote/MinecraftBedrockServer/issues/19
https://github.com/TheRemote/MinecraftBedrockServer/issues/70
https://github.com/TheRemote/MinecraftBedrockServer/issues/79
https://github.com/TheRemote/MinecraftBedrockServer/issues/101
https://github.com/TheRemote/MinecraftBedrockServer/issues/103

Definitely standard running fare for Bedrock server and has been coming up over and over again for years.  It's a bug in the Bedrock server itself and is well known basically.  Hopefully that helps!
