### ISSUE TITLE
FixPermission script and sudoers

### ISSUE THREAD

**Issue by ThHareau** [TheRemote/MinecraftBedrockServer#107]
Hello, 

I'm quite worried about adding the `fixpermissions` and `start.sh` scripts to the sudoers file. If someone manage to get access to this repo, this could have a bad impact.

For `fixpermissions.sh`, I think it would be safer to only have this line in the sudoers file: 
```
minecraft-be ALL=(ALL) NOPASSWD: /usr/bin/chown -R userxname dirname/minecraftbe/servername
```

I tried it locally and it works fine. Then the rest of the sudo commands can be run without sudo, as long as they are run with the user `userxname`. 
If you are ok with this suggestion, I can start a PR. 

For the `start.sh` script, I don't really understand why this is needed. Do you have any clue?

**Comment by TheRemote** [comment]
The server can't restart itself for the daily restart without access to start.sh.  sudo systemctl start yourserver will fail without it meaning the server can't reboot itself.  If you don't use that functionality you can take it out too.
