### ISSUE TITLE
Docker version 

### ISSUE THREAD

**Issue by pipidaxian** [TheRemote/MinecraftBedrockServer#108]
Hi! Thanks for your work! 
If possible, could you please provide a docker version on arm64？
I want to apply it on my arm vps with docker

**Comment by pipidaxian** [comment]
And how can I totally uninstall the Minecraft Bedrock Server on arm64? Including uninstallation of QEMU.

**Comment by kwilliams1987** [comment]
Would also love a containerized version. Being able to get the QEMU host setup and the server would be amazing.

**Comment by TheRemote** [comment]
Yes, it probably is time for me to do this.  It has been long requested.  Thanks for letting me know and reminding me people want this!

**Comment by Atten007** [comment]
@TheRemote when‘ll the docker version of your Java and Bedrock Server be out?

**Comment by TheRemote** [comment]
Great question.  So I can't say exactly when but I can say that it has been on my mind and has basically been completely planned out.  I bounced some ideas and kind of fleshed this out here:

https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/#comment-13367

This was about 6 days ago.  I think it will be relatively easy (this will mostly be a port of my existing projects).  If I make a fancy "portainer" GUI for it it will probably take longer but it would be *really* cool.  Maybe I will just start with a straight port and not worry about the portainer yet.

This isn't a completely clean answer to your question but at least gives an idea of what it is going to look like.  I'm planning on using Docker volumes for persistent storage that can be mounted with the host OS (to allow editing server.properties and routine things people take for granted).

This item is higher on my agenda and I'll probably start writing the Docker template this week.  I'll definitely stop by and give some updates here when I start about how it's going!

**Comment by TheRemote** [comment]
Completed.

https://github.com/TheRemote/Legendary-Bedrock-Container

At least for the Bedrock one for the person who asked about the Java one (it's coming though for sure).  Thanks for everyone for asking for this and reminding me!

**Comment by TheRemote** [comment]
Java version is also now completed at https://github.com/TheRemote/Legendary-Java-Minecraft-Paper
