### ISSUE TITLE
I can't open server in RasberryPi

### ISSUE THREAD

**Issue by Sabone** [TheRemote/MinecraftBedrockServer#11]
ERROR: Id.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/id.so.preload cannot be preloaded (cannot open shared object file): ignored.
NO LOG FILE! - setting up server logging...

Unhandled prefetch abort: unknown 1 (0x001) at 0x604eb1a6

My device is RaspberryPI 3B+

**Comment by TheRemote** [comment]
So the Raspberry Pi support is broken and won't be fixed because it is going to be replaced with a much better solution soon here.  Basically we can run a native ARM version on the Pi now and I'm currently writing this up.  Stay tuned!

**Comment by counterfitninja** [comment]
@TheRemote do you have a time scale for the write up, or is it reliant on other factors?

**Comment by counterfitninja** [comment]
HI James, any update on the new version of Minecraft Bedrock for Raspbeery Pi? I have a 4 and would love to have this running as a bedrock server.

**Comment by mfilej** [comment]
Just stumbled upon this and I'm wondering wether a native arm version is already doable? I'm struggling to find other resources mentioning this.
