### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by ActionHDYT** [TheRemote/MinecraftBedrockServer#114]
BedrockServer.service - BedrockServer Minecraft Bedrock Server
   Loaded: loaded (/etc/systemd/system/BedrockServer.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-12-31 11:52:48 CET; 44min ago
  Process: 27279 ExecStart=/bin/bash /home/BedrockServer/minecraftbe/BedrockServer/start.sh (code=exited, status=1/FAILURE)

**Comment by TheRemote** [comment]
Impossible to say.  There's no information there other than it failed to start.

Have you tried launching the server manually?  What's your distro/java?  It's pretty unusual to have problems on a mainline distro that's functioning correctly.

**Comment by ActionHDYT** [comment]
If i start it manually It Shows me this Error: 
glibc_2.27 Not found

**Comment by ActionHDYT** [comment]
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -T term       Use term as $TERM for windows, rather than "screen".
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -U            Tell screen to use UTF-8 encoding.
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -v            Print "Screen version 4.05.00 (GNU) 10-Dec-16".
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -wipe [match] Do nothing, just clean up SockDir [on possible matches].
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -x            Attach to a not detached screen. (Multi display mode).
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: -X            Execute <cmd> as a screen command in the specified session.
Jan 03 19:57:27 rs-zap753258-1 bash[6108]: Error: Unknown option Logfile
Jan 03 19:57:27 rs-zap753258-1 sudo[6100]: pam_unix(sudo:session): session closed for user root
Jan 03 19:57:27 rs-zap753258-1 systemd[1]: BedrockServer.service: Control process exited, code=exited status=1
Jan 03 19:57:27 rs-zap753258-1 systemd[1]: Failed to start BedrockServer Minecraft Bedrock Server.
-- Subject: Unit BedrockServer.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit BedrockServer.service has failed.
-- 
-- The result is failed.
Jan 03 19:57:27 rs-zap753258-1 systemd[1]: BedrockServer.service: Unit entered failed state.
Jan 03 19:57:27 rs-zap753258-1 systemd[1]: BedrockServer.service: Failed with result 'exit-code'.
Jan 03 19:58:52 rs-zap753258-1 su[6193]: Successful su for root by BedrockServer
Jan 03 19:58:52 rs-zap753258-1 su[6193]: + /dev/pts/0 BedrockServer:root
Jan 03 19:58:52 rs-zap753258-1 su[6193]: pam_unix(su:session): session opened for user root by root(uid=1001)
Jan 03 19:58:52 rs-zap753258-1 su[6193]: pam_systemd(su:session): Cannot create session: Already running in a session

**Comment by TheRemote** [comment]
Hmmm, that's an interesting one.  It looks like you have a non-standard version of screen.  Which distro is this?

It's also too old of a distro to run Minecraft.  `glibc_2.27 Not found` means you don't have the version of C installed that Minecraft was compiled against.  

Can you post the output from your:

`cat /etc/os-release`

and 

`uname -a`?

**Comment by ActionHDYT** [comment]
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by ActionHDYT** [comment]
Linux rs-zap753258-1 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux

**Comment by TheRemote** [comment]
I wonder why Stretch doesn't have an update in LTS for screen.  It's too old though.  Look at what version of glibc stretch uses at https://packages.debian.org/source/stretch/glibc:

`2.24`

Stretch's LTS support ends in June of this year.  This is basically the Debian equivalent though of still running Ubuntu 16.04.  The glibc is too old for the newer Minecraft versions.  You'd have to download a build that is several years old for it to run on that.

Debian 10 (buster) has glibc 2.28 and will work as will all newer ones.  It looks like you will have to upgrade though even though you're caught at the very tail end of LTS for Stretch.  Hopefully that gets it for you!

**Comment by ActionHDYT** [comment]
How can i upgrade without loosing my data?

**Comment by TheRemote** [comment]
Is this a VPS or dedicated server you are leasing?  Or do you actually have this server physically?  If you are leasing a private server it's honestly easier to just rent a new one and then transfer everything and delete the old one.

Either way you'd want to make sure you have everything backed up.  Things can definitely go wrong upgrading old systems.  

Here's the instructions, but you shouldn't try them until you can say "I am not concerned about losing my data because I have made the proper backups":  https://www.cyberciti.biz/faq/update-upgrade-debian-9-to-debian-10-buster/

It's supposed to be easy, but that's assuming everything on the system is working correctly.  It seems to be best I can tell but you would know that better than I would.  Either way, don't risk it without proper backups first.  It's all at your own risk and I wouldn't risk it in my job without backups, but if you have those it should be pretty easy and is only a small handful of commands in the link above.

**Comment by ActionHDYT** [comment]
Its a server from ZapHosting

**Comment by ActionHDYT** [comment]
Are there any important settings I should save or just my files?

I have used the server only for the java server AllTheMods3

**Comment by ActionHDYT** [comment]
With Debian 10 it finally worked! Thanks for your help!

**Comment by TheRemote** [comment]
I was really relieved to see this!  I got a little nervous when you asked about the backups as I have personally ran into problems doing upgrades like this many times.  I mean usually it's fine but the small % where it's not are really dicey if there's no backups.

Congratulations on getting it working, enjoy and have fun!
