### ISSUE TITLE
Install script stalls downloading latest version of Minecraft Bedrock Server

### ISSUE THREAD

**Issue by chriswilson2020** [TheRemote/MinecraftBedrockServer#116]
Tried on multiple configurations on different days and always the script stalls downloading bedrock server. See attached screenshot
![bedrock](https://user-images.githubusercontent.com/73828727/151309789-128b38cb-ad41-4dfd-a108-46def0bdee4f.PNG)
.

**Comment by TheRemote** [comment]
Hmmm.  We haven't seen this for a while.  A long time ago Microsoft used to constantly block any type of script from hitting the Minecraft web site and that was the last time I've seen this.

I almost wonder if it's DNS or some sort of HTTPS certificate issue (but I think you'd get more of an error for that).

If you haven't tried for a while would you be willing to try again and see if this still happens?  That seems like around the time when we were having massive DNS attacks and I wonder if it would just work normally now.  Thanks!
