### ISSUE TITLE
Do not unzip allowlist.json 

### ISSUE THREAD

**Issue by shaman79** [TheRemote/MinecraftBedrockServer#118]
Hello,
whitelist.json was replaced by allowlist.json - now the script overwrite allowlist.json during unpack which causes users not being able to log-in.

This line should be changed:
 unzip -o "downloads/$DownloadFile" -x "*server.properties*" "*permissions.json*" "*whitelist.json*" "*allowlist.json*" "*valid_known_packs.json*"

**Comment by TheRemote** [comment]
Indeed, thank you for letting me know!  I've fixed this issue in the latest version.
