### ISSUE TITLE
Enable/Disable Automatic Updates

### ISSUE THREAD

**Issue by awesomejt** [TheRemote/MinecraftBedrockServer#122]
Perhaps this feature exists but didn't see it in options - allow script to enable/disable automatic updates of the Minecraft dedicated server.

**Comment by TheRemote** [comment]
It does not but this is also a good idea.  It wouldn't be too hard to add something like this.  There are already a couple of flags used at various places in SetupMinecraft.sh and this could be done either via a flag in SetupMinecraft.sh (making it permanent until you run SetupMinecraft.sh again, this would probably be a decent way to do it) or through start.sh although I like that a little less but if there were complications adding it the way I'm thinking then.

I think I can do this one as well and I'll investigate getting it added here!

**Comment by coreyb42** [comment]
PSA, in case anyone else is reverting their server to the old version, you just have to comment out these two lines by adding `#` to the start of the line: https://github.com/TheRemote/MinecraftBedrockServer/blob/master/start.sh#L106-L107

And to revert, you should have the old version in the `downloads` folder in your server folder.

**Comment by TheRemote** [comment]
Well that certainly shows that this and the other workaround should be possible.  It sounds like I basically already am keeping a backup of the previous server in the downloads folder!  I'd just need to add a flag or some way to trigger it.

This is a great workaround though for the moment.  Thanks for sharing!

**Comment by awesomejt** [comment]
Reverting by commenting out the lines and unzipping the previous server zip worked for me. I also commented out the update script until 1.19 client drops.

**Comment by TheRemote** [comment]
Excellent, thanks for that!  Before the next time this happens we will have something in place ready to deal with this but this should be a workaround until then (and you can see exactly how it's going to work when it's in the script, it will just have a way to trigger this that is far easier than having to go comment out individual lines of code).

Thanks everyone!
