### ISSUE TITLE
Revert to previous server version

### ISSUE THREAD

**Issue by awesomejt** [TheRemote/MinecraftBedrockServer#123]
It would be nice to be able to revert to a previous server version. This recently became needed since BDS is pushing out "future" updates which have no corresponding client. This basically makes BDS unplayable until The Wild Update is released. I still have my 1.18 zip in my downloads, so it would be nice if the script could offer a "revert" feature.

**Comment by TheRemote** [comment]
Normally I'd say this wouldn't be possible but you phrased this just right.  It *would* be possible to back up the previous version from an update.  This could be stored in the "downloads" folder or could even just be bedrock_server.bak as the previous version.

I will keep this open and investigate this but I think I can manage this and that it sounds like a good idea.  Microsoft does leave people in a bad spot on this quite often.  I'm not sure if their build servers aren't synced up quite right or if someone actually changes it or what it is but yeah I could definitely see the practical use of this.

I will investigate!

**Comment by starkey-01** [comment]
Just encountered this issue also. The [Minecraft Dedicated Server page](https://www.minecraft.net/en-us/download/server/bedrock) states it only serving up the Wild beta however the download URLs are still available if you look up the long version number. For example [Minecraft 1.18.33.02](https://minecraft.fandom.com/wiki/Bedrock_Edition_1.18.33).

`https://minecraft.azureedge.net/bin-win/bedrock-server-1.18.33.02.zip`

**Comment by TheRemote** [comment]
That's a great trick.  I'll post this on my blog too for people who want to try this!

**Comment by awesomejt** [comment]
Thanks, I would have just submitted a PR, but I just didn't have the time and I wasn't sure if you were open to contributions.

**Comment by TheRemote** [comment]
Hey dbroome,

Most likely it's replacing your manual extraction.  You would want to disable the update check temporarily for this as it's probably replacing your manual extraction.

The script will support this as yes it's a bit of a pain to do manually since there's never really been too much of a need for it (at least not longer than a few hours or maybe a day was the previous record which has been shattered by this event).  

I'm just pretty sure that even if I finish it today this is probably just going to be fixed and no later than tomorrow as that is the last day of the conference.

Thanks everyone for working on this and bearing with me!

**Comment by dbroome1978** [comment]
That did it.  Thank you

**Comment by starkey-01** [comment]
I just ran these three steps from start.sh inside the servername folder and replaced $DownloadFile $DownloadURL, dirname and servername. 

The scripts won't reinstall the latest version if it is already in the downloads folder until a newer version is available so this would have be repeated when they release the next version. The other ticket around automatic updates should resolve this. 

``` bash
        curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.$RandNum.212 Safari/537.36" -o "downloads/$DownloadFile" "$DownloadURL" 
         unzip -o "downloads/$DownloadFile" -x "*server.properties*" "*permissions.json*" "*whitelist.json*" "*valid_known_packs.json*" "*allowlist.json*" 
         Permissions=$(chmod u+x dirname/minecraftbe/servername/bedrock_server >/dev/null)
```

**Comment by TheRemote** [comment]
Added with PR #124 (thanks smallsam!)
