### ISSUE TITLE
How to uninstall the whole server? 

### ISSUE THREAD

**Issue by pipidaxian** [TheRemote/MinecraftBedrockServer#126]
Hi, I want to switch to the Java version. So I need to remove the whole installation, including the qemu. What can I do?

**Comment by TheRemote** [comment]
Are you using it on a Pi?  That is the only time QEMU is used.  You pretty much just delete the folders.

There is also /etc/systemd/system/yourserver.service /etc/sudoers and /etc/sudoers/minecraftbe.  Those are the only files it creates basically.

If you're on a Pi you'd just type sudo remote qemu-user-static.  That's pretty much it!

**Comment by pipidaxian** [comment]
Thanks for your reply, I am not using a pi, I am using an ARM server with ubuntu 20.04. I think your suggestion is helpful for me, thanks.

**Comment by TheRemote** [comment]
No problem, that should take care of it!  I tried to keep it pretty light on that kind of stuff and easy to remove / self contained.  The only two files I mentioned were out of absolute necessity and they are easy/safe to remove.

Take care!
