### ISSUE TITLE
Version of LibSSL not available anymore

### ISSUE THREAD

**Issue by theblujuice** [TheRemote/MinecraftBedrockServer#129]
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb does not exist anymore

**Comment by TheRemote** [comment]
Fixed, thanks!

**Comment by dbroome1978** [comment]
I'm sure if you want a new issue but this package doesn't exist anymore. Any way to use a new versions of openssl?
