### ISSUE TITLE
Possible network problem on Google Cloud

### ISSUE THREAD

**Issue by SiberianCoffe** [TheRemote/MinecraftBedrockServer#13]
I have a Google Cloud VPS which has a private IP address on it which then goes to a public IP and I think this gives me the problem that I can't connect, what can I do?

**Comment by TheRemote** [comment]
You definitely need a public IP that people can access for it to work.  From how you're describing the setup I am guessing that this server's IP is using Network Address Translation (NAT).  Usually this makes the VPS cheaper but without a public IP there's nothing for outsiders to connect to.

Google should have an option available for you to have a public facing IP address (they might charge for it, but it should be there).
