### ISSUE TITLE
Makes hosted Bedrock/MCPE servers show up as LAN servers

### ISSUE THREAD

**Issue by jingsno** [TheRemote/MinecraftBedrockServer#133]
"Feature enhancement request"

I use this utility https://github.com/jhead/phantom to make all my different Bedrock servers show up as LAN games on my local subnet. I put the executable phantom-linux into the minecraftbe directory, and add/change the following in the start.sh file in each ServerXX directory:

```

echo "Starting Minecraft server.  To view window type screen -r Server01"
echo "To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D"

# CHANGE: Grab the serverport
serverport=`sed -n 's/^server-port=\(.*\)/\1/p' <server.properties`

CPUArch=$(uname -m)
if [[ "$CPUArch" == *"aarch64"* ]]; then
    cd /home/administrator/minecraftbe/Server01
    if [ -n "$(which box64)" ]; then
        BASH_CMD="box64 bedrock_server"
    else
        BASH_CMD="LD_LIBRARY_PATH=/home/administrator/minecraftbe/Server01 /home/administrator/minecraftbe/Server01/bedrock_server"
    fi
else
   # CHANGE: Add phantom-linux
   # OLD: BASH_CMD="LD_LIBRARY_PATH=/home/administrator/minecraftbe/Server01 /home/administrator/minecraftbe/Server01/bedrock_server"
   BASH_CMD="../phantom-linux -server localhost:$serverport >/dev/null & LD_LIBRARY_PATH=/home/administrator/minecraftbe/Server01 /home/administrator/minecraftbe/Server01/bedrock_server"

```

I then run Server01 on 19142/19143, Server02 on 19152/19153, Server03 on 19162/19163, etc
The phantom-linux runs on 19132 and displays all the different servers  under "LAN games" without having to manually specify them on the Servers page on the client.

**Comment by gitalpaca** [comment]
Thank you for posting this! I found phantom a while back and have used it like this, but only manually. It would be nice to see it integrated into the startup script or at least have an option to download and enable it in the setup process.

My Linux skills are shaky at best, so this may be a dumb question. Should there be something in the stop.sh script to shut it down? I know phantom constantly checks for server availability once it starts. Not sure if that would fill up a log somewhere or if multiple copies would end up starting during each of the nightly reboots.

**Comment by TheRemote** [comment]
Thanks for sharing!
