### ISSUE TITLE
Command ' bash' not found 

### ISSUE THREAD

**Issue by cenobitedk** [TheRemote/MinecraftBedrockServer#136]
No sure if this is local problem or not, can you help me diagnose?

I'm running Ubuntu 20.04.5 LTS and I just ran the Software Updater, but I'm still getting the same error.

```sh
$ curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh | bash
bash: curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh : No such file or directory

Command ' bash' not found, did you mean:

  command 'bash' from deb bash (5.0-6ubuntu1.2)
  command 'rbash' from deb bash (5.0-6ubuntu1.2)

Try: sudo apt install <deb name>
```

**Comment by cenobitedk** [comment]
```
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by TheRemote** [comment]
I think it's your spacing.  Can you try:

`curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh|bash`

It's highlighting it as red in the GitHub code editor too.  Notice the spacing in this command:

```
Command ' bash' not found, did you mean:
command 'bash' from deb bash (5.0-6ubuntu1.2)
```

You definitely do have 'bash' it seems but you don't have ' bash'.  Can you give that a try and see if it works?

**Comment by cenobitedk** [comment]
Not sure why, but for some reason it worked fine today, after a reboot. Sorry that it took me so long to test. I have switched over to the docker servers instead.

Btw, I'm running multiple containers of yours along with this, https://github.com/illiteratealliterator/manymine, and it works great on both iPad and Nintendo switch!

**Comment by TheRemote** [comment]
Fantastic, thanks for following up with me and letting me know this got it for you!

That's awesome, thanks for sharing the link to manymine as well!
