### ISSUE TITLE
sudo usage and even attempt to replace system library?

### ISSUE THREAD

**Issue by sdettmer** [TheRemote/MinecraftBedrockServer#137]
Hi,
 
thank you for your great work. I took a look to `SetupMinecraft.sh` to check if I could safely execute it. First, it attempts several sudo, for example to create a systemd unit (I guess to start a user process). Why not simply using a user unit, the minecraftbe.service sets a user anyway and should not need any root access.

A bit later I met:

    sudo mkdir /lib64
    # Create soft link ld-linux-x86-64.so.2 mapped to ld-2.31.so, ld-2.33.so, ld-2,35.so
    sudo rm -rf /lib64/ld-linux-x86-64.so.2
    sudo ln -s $DirName/minecraftbe/$ServerName/ld-2.31.so /lib64/ld-linux-x86-64.so.2
    sudo ln -s $DirName/minecraftbe/$ServerName/ld-2.33.so /lib64/ld-linux-x86-64.so.2
    sudo ln -s $DirName/minecraftbe/$ServerName/ld-2.35.so /lib64/ld-linux-x86-64.so.2

_NB: "ln -s" (without -f) will not overwrite the file, so typically it will use the first that exists and fail afterwards (apparently there is no error handling in the script). Usually the most recent version should be used, so they should be tried in reverse order I think, but to make it functionally safe, "-f" would be needed, which then could overwrite a system library, as I like to describe in a bit more detail:_

I think this attempts (for ARM / amd64 emu, but anyway) to overwrite the system-wide linux loader "ld-linux" for all system processes by a version from unknown source with unknown properties (possibly a Microsoft version).  The systems version would be available as "libc6:amd64:" (Debian 11, name could differ in Ubuntu, but I think it is unlikely). Also it should not be needed. I know that stand-alone mode could be disabled at build time, Debian does not do so, so any binary can be ran by `~/ld-linux-alt.so ~/mybinary`, beside that QEMU surely offers a correct way to run a binary without all that.
I propose to remove the need for root access and instead recommend to create a dedicated user where to install and run everything. Instead of installing packages, the script could tell to please run `apt install curl unzip screen net-tools gawk openssl pigz` (if the latter is really needed; the others possible are often already installed).

I saw you also worked on a container. Possibly a very similar approach could be used here without a container based on debootstrap and schroot if there should really a need to replace system's libraries. By this, the installation would not interfere with other processes on the system.

However, I think this is not needed, so any need for root permissions can be removed.

**Comment by TheRemote** [comment]
You can't run the script as root.  You can only run the script as sudo.  There is a check to prevent you from setting this up as root.

The server doesn't run with root permissions.  They are only used during setup to create the /etc/sudoers.d/minecraftbe file and the systemd service.

These 3 commands are the only ones allowed to be ran as sudo:

`$UserName ALL=(ALL) NOPASSWD: /bin/bash $DirName/minecraftbe/$ServerName/fixpermissions.sh -a, /bin/systemctl start $ServerName, /bin/bash $DirName/minecraftbe/$ServerName/start.sh`

The correct way to do this is to create a special account to run the setup file.  You can't run it as root anyway.  

Most people create a "minecraft" account that doesn't have permissions to anything else.  You can temporarily add that account to the sudoers group and then run SetupMinecraft.sh.  After it's finished people remove the account from the sudoers group altogether.

None of the QEMU stuff is used unless you are using an ARM platform.  This is a legacy project.  I always recommend people use Docker.  

It's been like this for a long time but any security issues like this were resolved years ago.  It's a sudoers whitelist.   No, you cannot set it up as root, that is not allowed.  You are supposed to create a user to run it as sudo with just like you said and then kick them out of the sudoers group.  This is a pretty standard service setup.

Hopefully that helps!

**Comment by sdettmer** [comment]
Hi,
thank you for your quick reply. I'm afraid to completly misunderstood what I tried to say.

First, let me emphasize that I really like you big effort to make it available in an easy way. I hope many will find and use it and apparently there is a huge, happy and growing user base.

However, I'm afraid they open a security treat by utilizing root powers that should not be needed. Technically a binary must be started a user process, and for this, no root permissions are needed. Users can enforce libraries without root, users can setup systemd units without root and even install and download packages without root (not to system's default directories of course, so it will not affect other users, but to their own directories).

So actually, the script requires `sudo`, possibly for no real need. Giving any root access to a dedicated minecraft user breaks the security of the system, and be it only for the purpose of running one single shell script. For example, the minecraft account has write access to the fixpermissions.sh script, so the account can easily modify it and use it to get any access it wants to.

So to put it clear, the variable-replaced version of:

  $UserName ALL=(ALL) NOPASSWD: /bin/bash $DirName/minecraftbe/$ServerName/fixpermissions.sh

in sudoers gives any (malicous) process running under $UserName full root access; all it needs to do is to modify `fixpermissions.sh` or replace it (`cp install-backdoor.sh fixpermissions.sh`).

_(I don't see recommendation of a decicated user in https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/; if creating one, this user will have no way to gain priviledges by sudo; so I'm sure many less experienced users just execute the `curl | bash` chain under their normal account, because only on this, sudo works by default)_

I think in standard service setups there is no way for the service to gain any root access; everything else usually can be considered a security issue and should be fixed (and that's why I wrote).

So I think it would be good trying to protect the users as much as possible, and I think removing root access is a good protection.

**Comment by TheRemote** [comment]
You are free to change them and see what problems it creates.  If you are concerned about fixpermissions.sh then remove it from your script.  You can fix the permissions manually if they break.  Most people don't want to deal with that.

These are just templates.  People change them to suit their needs.  Your needs are not the same as everyone needs and what I've been trying to tell you is that we know 100% for a fact that standalone is not a good security model for Minecraft.  

In other words I'm saying with your needs you shouldn't even be willing to accept standalone.  That's why I might have seemed a little dismissive.  You can't know much if you don't understand how dangerous standalone is vs. containerization and that's not true just for Minecraft.  

This script is designed so that when it starts the server will work 100% of the time no matter how messed up the permissions have got on the Minecraft files.  I will not be removing that feature to fix ownership of the server files and yes that requires sudo.  

Most people don't want to deal with any of this stuff though which is why I literally recommend using Docker.  If you want to fork the script then by all means.  I don't recommend using standalone period.  Even in the documentation.  I will continue to recommend using Docker to everyone for both ease of setup and security.

**Comment by sdettmer** [comment]
Hi, thanks again for your quick and detailed answer. Thank you for suggestions how to change things and explanations. I don't like to fork (if so, only to propose patches, but I'd ask you before if there is a chance you merge them, as it costs efforts of course).

My target was trying to help by making proposals. For example, instead of creating a system wide systemd unit, someone could use:

```
mkdir -p ~/.config/systemd/user/
cat << EOT > ~/.config/systemd/user/bedrock.service
[Unit]
Description=Bedrock Server
After=multi-user.target

[Service]
RemainAfterExit=True
WorkingDirectory=$DirName/minecraftbe/$ServerName
ExecStart=$DirName/minecraftbe/$ServerName/bedrock_server

[Install]
WantedBy=default.target
EOT

systemctl --user enable bedrock.service
systemctl --user start bedrock.service
```

there is no root needed.

**Comment by TheRemote** [comment]
There's no root needed now.  It is a user mode service.  Look at the code:

```
[Service]
User=userxname
WorkingDirectory=dirname/minecraftbe/servername
Type=forking
ExecStart=/bin/bash dirname/minecraftbe/servername/start.sh
ExecStop=/bin/bash dirname/minecraftbe/servername/stop.sh
GuessMainPID=no
TimeoutStartSec=1800
```

See the User section under service?  It will be the account you run the script as.  This is why you run it as a new "minecraft" user for example.

Have you tried this?  It will work exactly as you're saying as long as you are the minecraft user or whatever user you ran the script as.  This is *not* a root service!
