### ISSUE TITLE
not working on ARM architecture

### ISSUE THREAD

**Issue by Tokke77** [TheRemote/MinecraftBedrockServer#138]
Seems there is a problem with installing on ARM achitecture because the installation of box64_deb fails from https://box64.debian.ryanfortner.dev/ 
I installed it manually  with the command: 
`sudo wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list
wget -qO- https://ryanfortner.github.io/box64-debs/KEY.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg 
sudo apt update && sudo apt install box64-rpi4arm64 -y`

then it works fine.  The setupscript needs to be updated I think.

**Comment by dannythunder** [comment]
Thanks! This solved the problem for me.

Splitting up the commands in case someone else just copy and paste:
`sudo wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list wget -qO- https://ryanfortner.github.io/box64-debs/KEY.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg  `

`sudo apt update && sudo apt install box64-rpi4arm64 -y`

**Comment by TheRemote** [comment]
I've fixed this line today, thanks for reporting it!
