### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by centuryx476** [TheRemote/MinecraftBedrockServer#14]
Hello,
Why is OpenSSL being installed ?
Is it needed to run a minecraft bedrock server ?

Thanks

**Comment by TheRemote** [comment]
Yes.  It didn't used to be, but a few updates ago this dependency was introduced to the Minecraft Bedrock server which broke people's server startup.

Here's the issue from when it happened: https://github.com/TheRemote/MinecraftBedrockServer/issues/7
