### ISSUE TITLE
Server will not update to version 1.21.31

### ISSUE THREAD

**Issue by TylerJohnson177** [TheRemote/MinecraftBedrockServer#144]
To my understanding, hotfix update 1.21.31 was released for bedrock servers on September 26th, but my server never updated. I looked into the issue a little bit more by running the start.sh manually, and I get the following output when the script checks for the latest version.

Latest version online is
Current install is: bedrock-server-1.21.30.03.zip
Installing
curl: (3) URL using bad/illegal format or missing URL
Starting Minecraft server.

Not sure if this is an issue for everyone or if it is something on my end, because I few days before the update released I purged some of the older bedrock-server downloads in the downloads folder, but left the version.html and the four latest installs. I do not think that would affect anything.

"version_installed.txt" displays "bedrock-server-1.21.30.03.zip"
OS: Debian 11

The server has been working and updating correctly for years before this issue came up, I have been using these scripts since 2021. If you could look into this issue that would be greatly appreciated.

**Comment by da99Beast** [comment]
I just checked and the latest on the server for download is 

Here is what my start.sh shows...

```
Checking for the latest version of Minecraft Bedrock server ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  589k    0  589k    0     0   963k      0 --:--:-- --:--:-- --:--:--  962k
Latest version online is
Current install is: bedrock-server-1.21.30.03.zip
Installing
curl: (3) URL using bad/illegal format or missing URL
```


Looking at the version.html that is in the download folder, the path changed...


`<a href="https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip"`

The start script looks for...

`LatestURL=$(grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*' downloads/version.html)`

So updating the LatestURL to be...

`LatestURL=$(grep -o 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*' downloads/version.html)`

should work....I will test locally.

**Comment by da99Beast** [comment]
That worked for me - I didn't capture the startup but it pulled the new version as expected.

**Comment by TylerJohnson177** [comment]
That worked for me as well, it downloaded and installed the update as expected.

**Comment by bokumin** [comment]
I had the same problem, but in my case I manually modified the script as follows and it worked
#  DownloadURL=$(grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*' downloads/version.html)    
DownloadURL=$(grep -o 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*' downloads/version.html)

**Comment by bokumin** [comment]
I had the same problem, but in my case I manually modified the script as follows and it worked
`#  DownloadURL=$(grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*' downloads/version.html)    
DownloadURL=$(grep -o 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*' downloads/version.html)`

**Comment by bokumin** [comment]
I think "update.sh" needs to be modified as well...

**Comment by bokumin** [comment]
I had a similar problem. If this is the first time we install, I think we need to modify "setup.sh" as well..

**Comment by skoelle** [comment]
There is already a pull request for SetupMinecraft.sh
https://github.com/TheRemote/MinecraftBedrockServer/pull/143

I commented there start.sh needs the change too.

**Comment by M-Taylor40** [comment]
@skoelle I've updated my branch to include the new URL in the start.sh script and checked the other files to make sure I can't see any other references to the old URL.

Hopefully @TheRemote can review and merge the changes.

**Comment by 0x233233** [comment]
To temporary solve this issues, i created a fork, patched it with the new url like M-Taylor40 has done and created a script to change the minecraft start, stop, etc. scripts to my repo. So other users have an easy solution.

https://github.com/0x233233/MinecraftBedrockServer

**Comment by TheRemote** [comment]
This is now fixed, could you give the latest version a try?
