### ISSUE TITLE
Bedrock server stuck at 1.21.23.01 wont update

### ISSUE THREAD

**Issue by DarkHorse-CC** [TheRemote/MinecraftBedrockServer#145]
Been a while since ive been on my server and i tried today and i keep getting version error when logging into server.  i checked my version and its stuck at 1.21.23.01 and ive tried rerunning the setup but still wont update.  any help would be great.

OS ubuntu

bedrock-server-1.21.3.01.zip is in the downloads folder

**Comment by DarkHorse-CC** [comment]
i did try the 1.21.31 issue listed and didnt work.

**Comment by DarkHorse-CC** [comment]
i had to update the start.sh with this

So updating the LatestURL to be...

LatestURL=$(grep -o 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*' downloads/version.html)

**Comment by 0x233233** [comment]
To temporary solve this issues, i created a fork, patched it with the new url like M-Taylor40 has done and created a script to change the minecraft start, stop, etc. scripts to my repo. So other users have an easy solution.

https://github.com/0x233233/MinecraftBedrockServer

**Comment by TheRemote** [comment]
This is now fixed in the latest version!
