### ISSUE TITLE
Server says it starts, but does not start

### ISSUE THREAD

**Issue by WonkyDubs** [TheRemote/MinecraftBedrockServer#148]
Hello, I am having an issue where the server software says it starts, but it does not actually start and does not create a new screen. There are no error messages when starting, it backs up the server, checks for updates, and says it is started. When I try to connect on LAN, I get unable to connect to server. I have completely deleted and uninstalled the server software twice. When trying to see the screen I get:
server@server:~/minecraftbe/BDS$ screen -list
No Sockets found in /run/screen/S-server.
server@server:~/minecraftbe/BDS$ screen -r BDS
There is no screen to be resumed matching BDS.
Please help!

**Comment by WonkyDubs** [comment]
Sorry, should have mentioned I have already updated the software each time with the new url. I have also tried the forked software, but both do not start the server or create a screen.

**Comment by TheRemote** [comment]
This is now fixed, could you give the latest version a try?

**Comment by WonkyDubs** [comment]
Fixed! thank you very much!
