### ISSUE TITLE
downloads folder error when downloading the server zip file

### ISSUE THREAD

**Issue by johstrau** [TheRemote/MinecraftBedrockServer#149]
I get the error below when I execute the SetupMinecraft.sh, so the server is actually never downloaded.

Error:
Checking for the latest version of Minecraft Bedrock server...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  591k    0  591k    0     0   800k      0 --:--:-- --:--:-- --:--:--  800k

Downloading the latest version of Minecraft Bedrock server...
curl: (3) URL using bad/illegal format or missing URL
unzip:  cannot find or open downloads/, downloads/.zip or downloads/.ZIP.
Grabbing start.sh from repository...

**Comment by da99Beast** [comment]
Is it the same as this open issue?

https://github.com/TheRemote/MinecraftBedrockServer/issues/144

**Comment by TheRemote** [comment]
This is now fixed, could you give the latest version a try?

**Comment by johstrau** [comment]
Yes works now
