### ISSUE TITLE
Stop script issue

### ISSUE THREAD

**Issue by JordanMajd** [TheRemote/MinecraftBedrockServer#16]
Ran on  two brand new Ubuntu VPS, one 18.04, one 19  and had the same issue using `stop.sh`:

```bash
./stop.sh: line 37: syntax error near unexpected token `done'
./stop.sh: line 37: `done'
```

Looking at the code, looks like the while loop formatting is the issue, updating line 33 from:

```bash
while [ $CountdownTime -gt 0 ] do
```

To:

```bash
while [ $CountdownTime -gt 0 ]; do
```

resolves the issue,  I can open a PR.

**Comment by TheRemote** [comment]
Thanks!
