### ISSUE TITLE
Server failed to start

### ISSUE THREAD

**Issue by massue** [TheRemote/MinecraftBedrockServer#18]
Hello,

After execute the script, the minecraft server failed to start, here are the logs : 

> Nov  5 19:23:11 lion systemd[1]: Starting cocoland minecraft server...
> Nov  5 19:23:11 lion bash[11224]: Checking for the latest version of Minecraft Bedrock server ...
> Nov  5 19:23:12 lion bash[11224]: --2019-11-05 19:23:12--  https://minecraft.net/en-us/download/server/bedrock/
> Nov  5 19:23:12 lion bash[11224]: Resolving minecraft.net (minecraft.net)... 54.230.218.164, 54.230.218.111, 54.230.218.87, ...
> Nov  5 19:23:12 lion bash[11224]: Connecting to minecraft.net (minecraft.net)|54.230.218.164|:443... connected.
> Nov  5 19:23:12 lion bash[11224]: HTTP request sent, awaiting response... 302 Moved Temporarily
> Nov  5 19:23:12 lion bash[11224]: Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
> Nov  5 19:23:12 lion bash[11224]: --2019-11-05 19:23:12--  https://www.minecraft.net/en-us/download/server/bedrock/
> Nov  5 19:23:12 lion bash[11224]: Resolving www.minecraft.net (www.minecraft.net)... 2606:2800:233:18f9:1142:8f:20aa:11e2, 152.199.20.92
> Nov  5 19:23:12 lion bash[11224]: Connecting to www.minecraft.net (www.minecraft.net)|2606:2800:233:18f9:1142:8f:20aa:11e2|:443... connected.
> Nov  5 19:23:12 lion bash[11224]: HTTP request sent, awaiting response... 200 OK
> Nov  5 19:23:12 lion bash[11224]: Length: unspecified [text/html]
> Nov  5 19:23:12 lion bash[11224]: Saving to: ‘downloads/version.html’
> Nov  5 19:23:12 lion bash[11224]:      0K .......... .......... .......... .......... .......... 1.96M
> Nov  5 19:23:12 lion bash[11224]:     50K .......... .......... .......... .......... .......... 2.31M
> Nov  5 19:23:12 lion bash[11224]:    100K .......... .......... .......... .......... .......... 11.0M
> Nov  5 19:23:12 lion bash[11224]:    150K .......... .......... .......... .......... .......... 11.4M
> Nov  5 19:23:12 lion bash[11224]:    200K .......... .......... .......... .......... .......... 2.91M
> Nov  5 19:23:12 lion bash[11224]:    250K .......... .......... .......... .......... ......     13.5M=0.07s
> Nov  5 19:23:12 lion bash[11224]: 2019-11-05 19:23:12 (3.86 MB/s) - ‘downloads/version.html’ saved [303314]
> Nov  5 19:23:12 lion bash[11224]: Minecraft Bedrock server is up to date...
> Nov  5 19:23:12 lion bash[11224]: Starting Minecraft server.  To view window type screen -r cocoland
> Nov  5 19:23:12 lion bash[11224]: To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
> Nov  5 19:23:12 lion systemd[1]: Started cocoland minecraft server.
> Nov  5 19:23:12 lion bash[11240]: Server is not currently running!
> Nov  5 19:23:12 lion systemd[1]: cocoland.service: Control process exited, code=exited status=1
> Nov  5 19:23:12 lion systemd[1]: cocoland.service: Unit entered failed state.
> Nov  5 19:23:12 lion systemd[1]: cocoland.service: Failed with result 'exit-code'.

I can't find where is the error, can you help me to resolve it ?

Thanks

**Comment by massue** [comment]
To find my problem I launch the server manually (LD_LIBRARY_PATH=. ./bedrock_server) then I could the the errors in logs : 
>./bedrock_server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./bedrock_server)
> ./lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./libCrypto.so)

So I fixed the errors thanks to https://bugs.mojang.com/browse/BDS-168 and https://bugs.mojang.com/browse/BDS-164
(I upgraded my server from Debian 9 to Debian 10)

**Now my server is running well**  ;)

But do you think if si possible to display in service logs the errors from the `./bedrock_server` ? 
This could help future people like me who is having trouble launching the server.

**Comment by TheRemote** [comment]
Thanks for posting and letting people know the solution.

I would like to add showing the errors from launching and the service error in the near future.  Thanks for the suggestion!
