### ISSUE TITLE
Multiple bedrock servers

### ISSUE THREAD

**Issue by mickeyreg** [TheRemote/MinecraftBedrockServer#19]
Hi,

I found a small problem when running 2 servers from startup script.

Config:
minecraft1:
```
server-port=19132
server-portv6=19133
```
minecraft2:
```
server-port=29132
server-portv6=29133
```

When minecraft2 starts first then:
```
[2019-11-19 13:49:36 INFO] IPv4 supported, port: 29132
[2019-11-19 13:49:36 INFO] IPv6 supported, port: 29133
[2019-11-19 13:49:36 INFO] IPv4 supported, port: 19132
[2019-11-19 13:49:36 INFO] IPv6 supported, port: 19133
```
So when minecraft1 starts it writes:
```
[2019-11-19 13:51:11 INFO] IPv4 supported, port: 0
[2019-11-19 13:51:11 INFO] IPv6 supported, port: 0
[2019-11-19 13:51:11 ERROR] Network port occupied, can't start server.
```
I've added to minecraft2.service line:
`After=network-online.target minecraft1.service`

After this modification both servers starts properly on system startup.
But manually I have to control not to start minecraft2 when minecraft1 is not running.
Maybe the better solution is set both server to non-standard port?

Regards,
Mickey

**Comment by weihao** [comment]
^ Same issue, following.

**Comment by ghaberek** [comment]
I've tried setting up multiple instances on a single host and I'm having the same problem. The server listens on the default ports *and* the other ports I've specified. Is this somehow tied to this project, or is it a bedrock server problem altogether?

**server.properties**

    server-port=19134
    server-portv6=19135

**bedrock_server.log**

    [INFO] IPv4 supported, port: 19134
    [INFO] IPv6 supported, port: 19135
    [INFO] IPv4 supported, port: 19132
    [INFO] IPv6 supported, port: 19133

**Comment by TheRemote** [comment]
This used to work originally.  It was actually pull requests submitted by people in the community when it was originally added.  Definitely they have changed something since earlier versions.

I don't think the port messages make a lot of sense.  For example, when I start a server with only a single instance I get:

```
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 supported, port: 19133
[INFO] IPv4 supported, port: 44153
[INFO] IPv6 supported, port: 40478
```

then if I restart it again I get:

```
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 supported, port: 19133
[INFO] IPv4 supported, port: 38013
[INFO] IPv6 supported, port: 59348
```
I'm guessing this second set of ports is dynamic.  I thought maybe it was related to online-mode so I set that to false but it still opened up the second set of mysterious ports.

I'll continue investigating here and see if we can come up with a solution other than just virtualizing.

**Comment by TheRemote** [comment]
Hey guys,

So this used to work but something has changed.  I also have noticed the multiple ports thing, but I get that even when I'm just running a single server and

**Comment by joshuacodes** [comment]
I haven't tested this exhaustively yet, but it looks like I can work around this bug by assigning all instances of the server a non-standard port. One of them, I think the first that boots, will also get the default, but at least it won't cause a subsequent instance to crash.

If that works for others, it may be worthwhile to note this as a workaround in the readme.

**Comment by TheRemote** [comment]
The best fix seems to be to not use the default port on any server.  The order in which you start it can change which ports get to listen on the "defaults".  Unfortunately the base bug hasn't been fixed still but not using the default ports seems to be a pretty good workaround!
