### ISSUE TITLE
Backups/restarts occur at 4AM UTC

### ISSUE THREAD

**Issue by nch0w** [TheRemote/MinecraftBedrockServer#25]
https://github.com/TheRemote/MinecraftBedrockServer/blob/846d009e2177d4b86a5b81cbd233827f3bafe7fd/SetupMinecraft.sh#L266

The server always restarts at 4AM UTC, regardless of what the computer's timezone is set to, since crontab times are in UTC.

**Comment by murkyl** [comment]
The crontab times should be in your local time zone. I would double check your timezone configuration for your distribution. My crontab works fine in local time versus UTC. I'm currently running Ubuntu 20.04 LTS.
