### ISSUE TITLE
Issues with QEMU Download

### ISSUE THREAD

**Issue by Wyvernslay3r** [TheRemote/MinecraftBedrockServer#26]
Hello - had some issues installing on a raspberry pi 3 - Debian appeared to have updated QEMU - had to search for the new FTP endpoint. I _believe_ this resolves the issue. If i'm wrong oh well, but figured I would share. 
wget http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_4.2-3_armhf.deb
#wget http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_3.1+dfsg-8_armhf.deb

**Comment by DanielAskTia** [comment]
This worked for me to continue the install script.  I don't think it'll be a fix for ARM64 though, but I'm not sure whether they have the same issue.

I'm installing this on a Odroid XUS4.

**Comment by TheRemote** [comment]
Updated project to mark this support as broken at the moment
