### ISSUE TITLE
Install script forces installation to current users homedir

### ISSUE THREAD

**Issue by makcuber** [TheRemote/MinecraftBedrockServer#27]
Hi, why does the install script force itself to install to the executing users homedir? I want the server files to be stored on a different partition than the one my homedir is on, but the script keeps trying to force itself into the homedir folder. II was able to modify the script to use a variable instead of the hardcoded ~ I found all over the place, it puts the files where I want them now. I strongly recommend you remove the default install path and make it the first thing the script asks you for instead

**Comment by TheRemote** [comment]
It's absolutely safe to bulk Ctrl+F the ~ character (it's not used anywhere else) and use the replace function to do this.
It could be added eventually as an option but it has only been requested a few times and is pretty easy to manage.  Thanks!
