### ISSUE TITLE
Can't connect to the server as if no ports is open?

### ISSUE THREAD

**Issue by kasperhartwich** [TheRemote/MinecraftBedrockServer#28]
Hi.

I used your guide to install on a brand new Digital Ocean instance with Ubuntu 18.04.3(LTS) and the install goes great.
The server starts as well, but I can't connect to the server:
> [2020-04-14 10:55:10 INFO] Starting Server
> [2020-04-14 10:55:10 INFO] Version 1.14.32.1
> [2020-04-14 10:55:10 INFO] Session ID 90c185f8-de4a-4767-ab45-a0dcc3960a6d
> [2020-04-14 10:55:10 INFO] Level Name: Emil
> [2020-04-14 10:55:10 INFO] Game mode: 1 Creative
> [2020-04-14 10:55:10 INFO] Difficulty: 1 EASY
> [2020-04-14 10:55:11 INFO] opening worlds/Bedrock/db
> [2020-04-14 10:55:13 INFO] IPv4 supported, port: 19132
> [2020-04-14 10:55:13 INFO] IPv6 supported, port: 19133
> [2020-04-14 10:55:13 INFO] IPv4 supported, port: 51358
> [2020-04-14 10:55:13 INFO] IPv6 supported, port: 38329
> [2020-04-14 10:55:15 INFO] Server started.

I also tried to `telnet localhost 19132`on the server and it fails? Do I need to open some ports?
> $ telnet localhost 19132
> Trying 127.0.0.1...
> telnet: Unable to connect to remote host: Connection refused

**Comment by Novemburr** [comment]
Very similar issue here. I dont have bedrock edition personally(setting it up for a friends kid) but the error they recieve is "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information" ($ could be an S the picture was not super quality)

My ports:
`
[2020-04-15 20:26:51 INFO] IPv4 supported, port: 25565
[2020-04-15 20:26:51 INFO] IPv6 supported, port: 19133
[2020-04-15 20:26:51 INFO] IPv4 supported, port: 19132
[2020-04-15 20:26:51 INFO] IPv6 supported, port: 46639
`
I've forwarded both 25565 and 19132 to 1337 and 1338 respectively.
I receive the same response from tellnet, remote nmap thinks the host is down.

**Comment by tbarbe01** [comment]
Make sure you are opening the UDP ports, not the TCP ports.  I had the same problem when I created my server on AWS.  Once I opened UPD Port's 19133 and 19132 it was able to connect.
