### ISSUE TITLE
Server failed to start because there was no screen to be resumed.

### ISSUE THREAD

**Issue by zak-35** [TheRemote/MinecraftBedrockServer#3]
I encountered the error message at the end of a server setup. The error went as follows:
```
Minecraft server failed to start after 20 seconds.
There is no screen to be resumed matching Server.
```
To reproduce this error I followed the steps listed in the read me file. Once I ran the script I choose the following options.
1) IPV4 port: 19132
2) IPV6 port: 19133
3) Start automatically: y
4) backup at 4am daily: y

Even though the startup script claims that the set up was not successful, it still creates the file and all of the associated data. When running the start.sh script it throws no error messages but ends immediately.

**Comment by ghaberek** [comment]
I had the same problem. It looks like `bedrock_server` requires libcurl4 which was not installed by default on my system. I just had to run `sudo apt install libcurl4` and the server starts correctly now.

**Comment by TheRemote** [comment]
Thank you!  libcurl4 has been added as a dependency to the installer script to prevent this in the future
