### ISSUE TITLE
Feature to do live backup without restarting the server

### ISSUE THREAD

**Issue by SandboChang** [TheRemote/MinecraftBedrockServer#30]
Hi,

In the Java implementation (which I followed this page: https://linuxize.com/post/how-to-install-minecraft-server-on-ubuntu-18-04/), I could use RCON to backup the server live without restarting it.

Would it be possible to do the same with bedrock server?

**Comment by TheRemote** [comment]
Absolutely.  Bedrock has some similar commands to tell the server to save everything:

https://minecraft.fandom.com/wiki/Commands/save
