### ISSUE TITLE
Rotate backups

### ISSUE THREAD

**Issue by pogzie** [TheRemote/MinecraftBedrockServer#33]
Please add backup rotation feature as the backups tend to pile up after some time.

**Comment by aghadjip** [comment]
a quick option would be to cron something like 
rm-rf ls -t <path to backups> | awk 'NR>10' 
replacing 10 with however many you want to keep. The above will keep the 10 newest, removing the rest. Dry run by removing the rm -rf command to see what it will do. I add the above to my crontab running weekly, i bash script move the archives to a longer term storage and delete.

**Comment by pogzie** [comment]
Thanks. I've currently thrown all the backups to my network drive for now. Im avoiding destructive `rm`s on the script but hopefully dev would consider this in the future to add an nBackupDays variable or something.

**Comment by TheRemote** [comment]
This is great, I need to add it to my [Raspberry Pi Java Minecraft server script](https://jamesachambers.com/raspberry-pi-minecraft-server-script-with-startup-service/) as well.  I'll add it here for the next version!

**Comment by TheRemote** [comment]
Added in latest version
