### ISSUE TITLE
Make it clear the Minecraft Server this installs is in Alpha testing.

### ISSUE THREAD

**Issue by AdenKoperczak** [TheRemote/MinecraftBedrockServer#34]
Please add to the README or someplace obvious that the server installed is in Alpha. 

I installed this several months ago and now I am running into issues with the server failing to save the world properly. Following the trail back, the server this script installs is from [Minecraft.net](https://minecraft.net/en-us/download/server/bedrock/). on Minecraft.net it is made clear that the server is in Alpha. I would not have installed the server (for what I was using it for) if I had known it was in Alpha.

**Comment by TheRemote** [comment]
Thanks, this has been added!
