### ISSUE TITLE
Allow user to specify alternate installation path (keep default as home)

### ISSUE THREAD

**Issue by starkey-01** [TheRemote/MinecraftBedrockServer#35]
Trying to install on a cloud service but had to edit the SetupMinecraft.sh script to force the installation into an alternate directory. Perhaps this could be an option when running file.

**Comment by eFiggy** [comment]
I hadn't realized this until a few moments ago and saw this issue. Please allow us to specify an installation directory, especially for those of us using cloud providers! Awesome script, by the way!

**Comment by TheRemote** [comment]
This has been added!
