### ISSUE TITLE
hi i have problem when i start my server on debian 9

### ISSUE THREAD

**Issue by ViruZzInGame** [TheRemote/MinecraftBedrockServer#36]
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Waiting for network interface to come up timed out - starting server without network connection ...
Checking for the latest version of Minecraft Bedrock server ...
--2020-06-29 16:04:02--  https://minecraft.net/en-us/download/server/bedrock/
Resolving minecraft.net (minecraft.net)... 13.249.4.64, 13.249.4.48, 13.249.4.41, ...
Connecting to minecraft.net (minecraft.net)|13.249.4.64|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
--2020-06-29 16:04:02--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 152.199.21.175, 2606:2800:233:1cb7:261b:1f9c:2074:3c
Connecting to www.minecraft.net (www.minecraft.net)|152.199.21.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305880 (299K) [text/html]
Saving to: 'downloads/version.html'

downloads/version.h 100%[===================>] 298.71K  --.-KB/s    in 0.06s

2020-06-29 16:04:03 (4.97 MB/s) - 'downloads/version.html' saved [305880/305880]

Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r devbds
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
root@omegaserv:~/minecraftbe/devbds# screen -r devbds
There is no screen to be resumed matching devbds.

**Comment by ViruZzInGame** [comment]
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Network interface not up, will try again in 1 second
Waiting for network interface to come up timed out - starting server without network connection ...
Checking for the latest version of Minecraft Bedrock server ...
--2020-06-29 16:04:02--  https://minecraft.net/en-us/download/server/bedrock/
Resolving minecraft.net (minecraft.net)... 13.249.4.64, 13.249.4.48, 13.249.4.41, ...
Connecting to minecraft.net (minecraft.net)|13.249.4.64|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
--2020-06-29 16:04:02--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 152.199.21.175, 2606:2800:233:1cb7:261b:1f9c:2074:3c
Connecting to www.minecraft.net (www.minecraft.net)|152.199.21.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305880 (299K) [text/html]
Saving to: 'downloads/version.html'

downloads/version.h 100%[===================>] 298.71K  --.-KB/s    in 0.06s

2020-06-29 16:04:03 (4.97 MB/s) - 'downloads/version.html' saved [305880/305880]

Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r devbds
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
root@omegaserv:~/minecraftbe/devbds# screen -r devbds
There is no screen to be resumed matching devbds.

**Comment by aghadjip** [comment]
There seems to be a dependency on the route command in the start.sh. Make sure its installed. You may also have to fully qualify the path if its not in your path (which route) 
`# Check if network interfaces are up
NetworkChecks=0
DefaultRoute=$(/sbin/route -n | awk '$4 == "UG" {print $2}')
while [ -z "$DefaultRoute" ]; do
    echo "Network interface not up, will try again in 1 second";
    sleep 1;
    DefaultRoute=$(route -n | awk '$4 == "UG" {print $2}')
    NetworkChecks=$((NetworkChecks+1))
    if [ $NetworkChecks -gt 20 ]; then
        echo "Waiting for network interface to come up timed out - starting server without network connection ..."
        break
    fi
done
`

**Comment by TheRemote** [comment]
This has been fixed!
