### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Loaxx** [TheRemote/MinecraftBedrockServer#40]
Hello, 

First of all, your script is simply amazing. I'm running into a very annoying issue though.
When the server idles, it's using about 3-4% cpu, but as soon as one player joins, it spikes to 100% and stays between 75 - 100%.

Maybe htop tells you something more.. I'm not sure if this is an issue with Minecraft Bedrock or your script, so sorry in advance.

Thanks
![100cpu](https://user-images.githubusercontent.com/68658949/88208058-f4849100-cc50-11ea-9dbd-ffb87a1f2540.jpg)

**Comment by idvorkin** [comment]
It's bedrock
