### ISSUE TITLE
Level Migration

### ISSUE THREAD

**Issue by JoshSchultz** [TheRemote/MinecraftBedrockServer#42]
I've setup a new server and attempted to migrate an existing level (local Win10 1909 hosted level, client v1.16.10) to the server (Ubuntu 20 hosted on a vSphere 6.0 server, also using Webmin to easier access settings & services) and although I've got things transitioned, there's a few tricks and caveats to note. This likely should be added to your documentation.

### To Migrate World from device to device:

1. Stop server
2. Copy world folder from: "C:\Users\%username%\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds".
The world folder will be a scrambled set of characters ending with an "=" sign. I recommend opening world in Minecraft so you know which one it is, then in Windows Explorer, sort by last modified date.
5. Copy that folder to the server Minecraft folder:
"minecraftbe\[key word specified during setup]\worlds"
7. Remove the "=" from the name of the folder.
8. Edit the file "server.properties", changing the field "level-name" (line 55) to the name of the world folder you copied over.
9. Save file
10. Start Server

### Caveats:
- All Inventory on player is lost. Recommended to store in a chest first for any players that have played on this world.
- Any Experience gained on player will be reset to 0 (Is this normal with other migrations??)
- Your spawn will reset to the World spawn point. Recommend noting your coordinates if possible.
- Operator status does not follow the world. You will need to reset this once the world is started using the "whitelist.json" & "permissions.json" files.

### Multi-Worlds Recommendation:
I would also suggest expanding your documentation to explain how to setup the multi-world servers as well. It took a little bit for me to figure it out since there's no details on the process. Thanks :)

### Kudos:
Thanks to those who've contributed to this. Setting up this server was relatively easy to do with the package and instructions that have been provided.

**Comment by obstler42** [comment]
> ### Multi-Worlds Recommendation:
> 
> I would also suggest expanding your documentation to explain how to setup the multi-world servers as well. It took a little bit for me to figure it out since there's no details on the process. Thanks :)

Could you please expand on what is necessary to setup multi world servers?

thx!

**Comment by TheRemote** [comment]
This is a really good guide.  I definitely want to expand the documentation on multi world servers and agree with you guys and will work on that.  Right now multiple instances are having issues for everyone due to a bug in the Bedrock dedicated server but I've put that in there and am going to add better instructions for when it's fixed here.
