### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Nunya-9018** [TheRemote/MinecraftBedrockServer#51]
plz update server the verison is old

**Comment by TheRemote** [comment]
You may need to manually update start.sh to the newest version or run SetupMinecraft.sh again.

It should always download the latest version but the download was broken earlier.  Can you update your start.sh script or run SetupMinecraft.sh and try again?

**Comment by Nunya-9018** [comment]
no i updated it but i mean  new minecraft verison came out can you update the files

**Comment by Nunya-9018** [comment]
it made it so me and my freinds cant join the server

**Comment by Nunya-9018** [comment]
sure i will later

**Comment by TheRemote** [comment]
Okay, wait, are you talking about the RTX beta version of Minecraft when you say the "new" version?

I have that too, and they haven't released the dedicated server for it unfortunately yet.  I've looked everywhere but if anyone can find it I would gladly add support in for it!

**Comment by Nunya-9018** [comment]
no i mean 1.16.200

**Comment by TheRemote** [comment]
You may need to restart the server but it's running on this version
