### ISSUE TITLE
Simplified server administration

### ISSUE THREAD

**Issue by traek** [TheRemote/MinecraftBedrockServer#6]
I'm wondering what you would think about making your script better compatible with [cockpit](https://github.com/cockpit-project/cockpit) to improve user-friendly server administration. It's already pretty close to there given you went with systemd services.

I was thinking that moving from crontab to systemd timers for the restart would be a good first step. I started working on it but thought I'd get your thoughts on if there was a compelling reason to stick with crontab. If not, I'd like to contribute a little, maybe even eventually offer to install/enable cockpit as part of your script.

Just a thought...

**Comment by TheRemote** [comment]
I love the idea!

There's no reason to stick with crontab in the code.  I just used something people were more familiar with and got the job done.

Any contributions are welcome if you have time, and thanks!

**Comment by timriker** [comment]
I use a @reboot tag in crontab and avoid systemd. This allows the entire setup to work as a user without root access.
