### ISSUE TITLE
Unable to connect to world error when trying to connect to my server.

### ISSUE THREAD

**Issue by thetechguy-cpu** [TheRemote/MinecraftBedrockServer#60]
Hi.
I have a ubuntu vps. I ran the script and all went well. I was able to start the server. It said server started, however when my friends try to connect to my external IP with the port 19132, it says unable to connect to world. Nothing shows up on the logs. Port 19132 is open on UFW. What am I doing wrong here?

**Comment by HockeyGuy10** [comment]
Are you port forwarding 19132 from your router to your server?

**Comment by thetechguy-cpu** [comment]
No. The server is in a separate network. Port 19132 is open on that. Does it have to be open on my router too?

**Comment by HockeyGuy10** [comment]
Yes.  Your router has to port forward all 19132 (TCP & UDP) traffic to your server or it will stop at the router.

**Comment by HockeyGuy10** [comment]
I might have missed a detail at the beginning.  Is Ubuntu VPS hosted somewhere other than your network?  Or does it have its own external IP separate from your router?

**Comment by thetechguy-cpu** [comment]
@HockeyGuy10  By Ubuntu VPS I mean a server with an external IP on a different network.

**Comment by thetechguy-cpu** [comment]
Hi.
I'm sorry to bring this back up, but does anyone have ideas to solve my problem?
Thanks.

**Comment by TheRemote** [comment]
You probably have ufw enabled if it's Ubuntu Server.  A:

`ufw allow 19132`

should probably do it!
