### ISSUE TITLE
Server fails to start: OPENSSL_1_1_1 Not found

### ISSUE THREAD

**Issue by obviator** [TheRemote/MinecraftBedrockServer#7]
Love work. Thank you!

Just upgraded to 1.12 from 1.11 using your script and afterwards the server silently failed to start on Ubuntu 18.04.

When I ran `bedrock_server` manually I got 

> OPENSSL_1_1_1 Not found

 from `libCrypto.so`

`sudo apt install openssl -y` upgraded openssl and fixed the issue.

Could I make a couple of feature requests?

1) Not sure what `bedrock_server` gives you in the way of return codes but any sort of check to see if it has started correctly would be great.

2) Include a check for `openssl` version

**Comment by TheRemote** [comment]
Thanks for the compliment!

I've added the openssl check into the latest version.

I'll look into adding some failure codes as I think that's a great idea!
