### ISSUE TITLE
Only using one CPU core

### ISSUE THREAD

**Issue by Fich420** [TheRemote/MinecraftBedrockServer#72]
Hello, I recently started using this program over one made for the windows environment. It works perfectly except for one issue, which is more than likely my own fault, I just cannot figure it out. 

My server.properties file can be found here
https://pastebin.com/raw/vDpsAGTs

As you can see max-threads is set to zero. However, when we open htop we can see that only core 24 is being used, and its being maxed out at 100%. 
https://ibb.co/bWw6Hg7

I know its being limited as the server will normally run PERFECTLY and the cores will run at maximum ~15%. The server is also very laggy (server sided lag, ex. mobs move slowly, slow reaction time, blocks take long time to drop entity, etc.)

**Comment by IceCruelStuff** [comment]
It's not this program's fault, it's the Bedrock Server's fault.

**Comment by Fich420** [comment]
> It's not this program's fault, it's the Bedrock Server's fault.

Is this a issue with any ubuntu based bedrock server? Was not having this issue on windows

**Comment by TheRemote** [comment]
This is an official bug with the dedicated server and is outside my control unfortunately.  The bug is here:

https://bugs.mojang.com/browse/BDS-2574

Still open status at the moment!
