### ISSUE TITLE
Invalid user userxname

### ISSUE THREAD

**Issue by terrykimura** [TheRemote/MinecraftBedrockServer#73]
https://github.com/TheRemote/MinecraftBedrockServer/blob/ad339020db34387ea991a9b5e57b9ebd84dc2e79/start.sh#L35

Who is `userxname`? This (predictably) causes the following error:
```
terry@os3-354-10066:~/minecraftbe/Bedrock-KIX$ ./start.sh 
[sudo] password for terry: 
chown: invalid user: 'userxname'
Checking for the latest version of Minecraft Bedrock server ...
<SNIP>
```

**Comment by NanoCode012** [comment]
I also got this error. Even, after I changed it to my real username, I can't start Minecraft now. 

```
# SetupMinecraft.sh
Start Minecraft server at startup automatically (y/n)?n
Setup is complete.  Starting Minecraft server...
Minecraft server failed to start after 20 seconds.
There is no screen to be resumed matching Test.
```

```
# start.sh
Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r Test
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
# nothing appear
```

**Comment by Goodsoldier** [comment]
same problem

**Comment by terrykimura** [comment]
@NanoCode012 @Goodsoldier The issue with the server not starting is likely because of https://github.com/TheRemote/MinecraftBedrockServer/issues/74, tl;dr `bedrock_server` lost its executable bit for some reason, and `chmod +x` fixes it. Now my Minecraft server runs, still with this error message `invalid user: 'userxname'`.

**Comment by NanoCode012** [comment]
Re-running Setup now works! The owner fixed the bug really quickly.

**Comment by TheRemote** [comment]
Hey guys,

Sorry about this, I was working with people on this bug via jamesachambers.com and didn't see it here.

This can happen if you reuse a old SetupMinecraft.sh script as well since the old version of the script didn't look for userxname in the systemd service.  Go ahead and remove the old version of SetupMinecraft.sh and run it with the fresh one and it should fix your service/userxname issue!
