### ISSUE TITLE
bedrock_server: Permission denied

### ISSUE THREAD

**Issue by terrykimura** [TheRemote/MinecraftBedrockServer#74]
Starting from the automatic restart at 0400 JST today (2021-04-06 19:00 UTC), the server suddenly refuses to work, with the single line "bedrock_server: Permission denied" appearing in logs:
```
tkimura@tower:~/minecraftbe/Bedrock1/logs$ grep -c $ * | tail
Bedrock1.2021.04.02.16.48.30.log:19
Bedrock1.2021.04.02.17.06.47.log:28
Bedrock1.2021.04.03.04.00.56.log:26
Bedrock1.2021.04.04.04.00.55.log:228
Bedrock1.2021.04.05.04.01.10.log:175
Bedrock1.2021.04.06.04.00.55.log:204
Bedrock1.2021.04.07.04.00.57.log:1
Bedrock1.2021.04.07.14.17.02.log:1
Bedrock1.2021.04.07.14.20.07.log:1
Bedrock1.2021.04.07.14.21.32.log:1
tkimura@tower:~/minecraftbe/Bedrock1/logs$ cat Bedrock1.2021.04.07.04.00.57.log
/bin/bash: /home/tkimura/minecraftbe/Bedrock1/bedrock_server: Permission denied
tkimura@tower:~/minecraftbe/Bedrock1/logs$
```

`bedrock_server` is owned by me, like (I assume) it has been before 0400 JST:
```
tkimura@tower:~/minecraftbe/Bedrock1$ ls -l bedrock_server
-rw-r--r-- 1 tkimura tkimura 69192536 Mar 20 06:28 bedrock_server
tkimura@tower:~/minecraftbe/Bedrock1$ whoami
tkimura
tkimura@tower:~/minecraftbe/Bedrock1$
```

I did a fresh run of the latest SetupMinecraft.sh on another server, and the exact same issue occurs. Anybody else experiencing this issue? Any ideas how to fix?

**Comment by iainwyatt** [comment]
Also seeing the same, we boot fresh each day with an auto shutdown and on boot today we see the same error on start. I tried the same steps, but I'm out of debugging options. I don't really know my way around Ubuntu to fix it.  Tried fixpermissions.sh as well.

**Comment by djryan012** [comment]
I can also confirm that starting today my server was not starting. 
Log showed:
/bin/bash: dirname/minecraftbe/servername/bedrock_server: No such file or directory.

ran the suggest fix by @iainwyatt of chmod +x ./bedrock_server and server started without issues.

**Comment by terrykimura** [comment]
D'oh, I did not notice that.
```
terry@os3-354-10066:~/minecraftbe/Bedrock-KIX$ ls -l bedrock_server
-rw-r--r-- 1 terry terry 69192536 Mar 20 06:28 bedrock_server
terry@os3-354-10066:~/minecraftbe/Bedrock-KIX$ chmod +x bedrock_server
terry@os3-354-10066:~/minecraftbe/Bedrock-KIX$ ls -l bedrock_server
-rwxr-xr-x 1 terry terry 69192536 Mar 20 06:28 bedrock_server
terry@os3-354-10066:~/minecraftbe/Bedrock-KIX$ 
```

Now it works fine!
