### ISSUE TITLE
can't run the installer

### ISSUE THREAD

**Issue by budaiphone** [TheRemote/MinecraftBedrockServer#75]
Hi,

Unfortunately I can not install the server.
I'm always stucked here:
"
Welcome to Ubuntu 20.10 (GNU/Linux 5.4.73-1-pve x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Apr 14 10:18:26 UTC 2021 on tty1
root@mc-pe:# ./SetupMinecraft.sh
Minecraft Bedrock Server installation script by James Chambers
Latest version always at https://github.com/TheRemote/MinecraftBedrockServer
Don't forget to set up port forwarding on your router! The default port is 19132
This script is not meant to be ran as root or sudo. Please run normally with ./SetupMinecraft.sh. If you know what you are doing and want to override this edit this check out of SetupMinecraft.sh. Exiting...
root@mc-pe:#
"
Any ideas?

Thanks in advance,
BL

**Comment by Andyhx888** [comment]
Did you fix the problem? I have the same problem.
