### ISSUE TITLE
Move variables to another script instead of re-writing start.sh and stop.sh

### ISSUE THREAD

**Issue by murkyl** [TheRemote/MinecraftBedrockServer#77]
A suggestion to move some of the scripts paths and variables to another shell script, maybe something called config.sh and then source the file and use variable substitution in the start.sh and stop.sh

As an example in the config.sh you could have:
NUM_BACKUPS=10
SERVER_NAME=servername
BASE_PATH=/dirname/minecraftbe/$SERVER_NAME

In the other scripts near the top do a:
source config.sh

Also replace any of the hardcoded paths and values with the variables.

This would eliminate the need to edit the other scripts and the installer could just echo these values out easily.

**Comment by CobraBitYou** [comment]
The variable source file doesn't have to be an executable script, it could be a simple .txt file. I was working on my own version of these scripts because it seems that they haven't updated this project in a while. I might try to finish them eventually.

**Comment by murkyl** [comment]
You are totally correct that it can be any file. I normally do put a .sh on it to indicate that it contains shell executable code. There has been some activity on this but I've already converted all the scripts in my install to use variables. I haven't tested out all the features in the script yet so I haven't done a fork and pull request. I may do that later. I've added in some code to automatically find the dir that the start/stop/restart.sh is called and then to source the config from that directory. Otherwise you have to hard code the path into the script or pass it in as a variable and I wanted to avoid that.

Doing this does the job:
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source ${SCRIPT_PATH}/config.sh

**Comment by TheRemote** [comment]
Absolutely.  If you guys completely configure it I would take a look at it!
