### ISSUE TITLE
Auto upgrades to the server do not set the execute bit

### ISSUE THREAD

**Issue by murkyl** [TheRemote/MinecraftBedrockServer#78]
When upgrading to the newest package. After unpacking the files, the bedrock_server file needs to have the execute bit set. Due to the fact that the files are in a Zip, the permission bits on the files are incorrect. The simple fix is to add the following line after unzipping. Letting ${BASE_DIR}/${SERVER_NAME} be the path to the server files.

chmod u+x ${BASE_DIR}/${SERVER_NAME}/bedrock_server

**Comment by TheRemote** [comment]
You're quite right, I actually have a permissions line *above* this which is obviously not going to help!

I've added this in, thanks!
