### ISSUE TITLE
Raspberry Pi 4 Setup Issue?

### ISSUE THREAD

**Issue by IBXCODECAT** [TheRemote/MinecraftBedrockServer#82]
I am new to Linux and ubuntu so I might be doing something extremely dumb, but I am using a raspberry pi 4 as well (8GB) with the latest version of ubuntu server and following the instructions that you have linked in the README.md file. I am getting the error 

`/home/ubuntu/minecraftbe/IBX-Server/bedrock_server: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory`.

After this I enter the directory where I have the server and run the `./start.sh` script. It says that the server is launched however when I try to change screens it says that `there is no screen with label IBX-Server to resume`.

Please help me, and thanks in advance

**Comment by Nunya-9018** [comment]
So the reason it doesn't work is this. 


ARM 64bit (BROKEN -- needs linker and other binaries used for emulation to be updated) this is taken from the read me

**Comment by TheRemote** [comment]
https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/

The other posters in this are right.  Generating the dependencies is pretty easy and I walk through how to do it there!

**Comment by IBXCODECAT** [comment]
Thanks!
