### ISSUE TITLE
Server does not start after successful installation

### ISSUE THREAD

**Issue by smolinde** [TheRemote/MinecraftBedrockServer#83]
After successful installation the start.sh crashes. See log below:

ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/home/pi/minecraftbe/schwebeplattform/bedrock_server: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

I even run my raspi 4 (8GB) with arm 64bit. This seems not to fix the issue. I hope for some help :)
Thank you a lot!

**Comment by murkyl** [comment]
What platform are you running? It seems like ARM on a Pi? The ARM builds are broken right now per the readme.

**Comment by smolinde** [comment]
I have the ARM processor and Raspberry Pi 4 (8GB). Will the project be repaired/updated so it would be possible to run a server on a raspi 4?

**Comment by murkyl** [comment]
The bedrock server code is compiled as Intel x86 architecture. It seems there are working Docker Images and such for the Java version, however the Java version doesn't allow interoperability with consoles and tablets. I'm not an expert on this in particular but if you want to run the Bedrock Edition server you may have to go with an x86 based machine for the moment or run it within a VM infrastructure that can emulate an x86 environment.

**Comment by smolinde** [comment]
I will try to install the x64 beta OS for the raspberry pi 4, if it works I will post something here.

**Comment by TheRemote** [comment]
The dependencies have been regenerated but check out https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/ for the full walkthrough on how to get the Pi part of it going for sure!
