### ISSUE TITLE
how to update this Server built tool ?

### ISSUE THREAD

**Issue by MasayaKondo999** [TheRemote/MinecraftBedrockServer#84]
thank you for bussiness , James .
 (I'm not native english speaker . It maybe sometimes mistakes . sorry)

I'm using your tool . but I don't know this tool updating .
Is it safe "git clone" again?   and , Should I copy "backups" directory out of Minecraft tool before clonig? 

Masaya Kondo

**Comment by MasayaKondo999** [comment]
and after updating 




worlds/miyavi/db/174675.ldb
worlds/miyavi/db/174917.ldb
worlds/miyavi/db/172837.ldb
worlds/miyavi/db/174730.ldb
start.sh: 47: pushd: not found
rm: cannot remove 'structures': Is a directory
rm: cannot remove 'resource_packs': Is a directory
rm: cannot remove 'definitions': Is a directory
rm: cannot remove 'behavior_packs': Is a directory
rm: cannot remove 'world_templates': Is a directory
rm: cannot remove 'treatments': Is a directory
rm: cannot remove 'premium_cache': Is a directory
rm: cannot remove 'minecraftpe': Is a directory
rm: cannot remove 'development_skin_packs': Is a directory
rm: cannot remove 'development_resource_packs': Is a directory
rm: cannot remove 'development_behavior_packs': Is a directory
rm: cannot remove 'downloads': Is a directory
start.sh: 47: popd: not found
Checking for the latest version of Minecraft Bedrock server ...
--2021-05-06 10:41:10--  https://minecraft.net/en-us/download/server/bedrock/
Resolving minecraft.net (minecraft.net)... 99.86.219.60, 99.86.219.36, 99.86.219.38, ...
Connecting to minecraft.net (minecraft.net)|99.86.219.60|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
--2021-05-06 10:41:11--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 23.48.213.215, 23.48.213.200
Connecting to www.minecraft.net (www.minecraft.net)|23.48.213.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘downloads/version.html’

downloads/version.html                              [ <=>                                                                                                 ] 301.83K  --.-KB/s    in 0.1s

2021-05-06 10:41:11 (2.49 MB/s) - ‘downloads/version.html’ saved [309071]

Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r miya
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
miyavi@miyaviserver:~/minecraftbe/miya$ screen -ls
There is a screen on:
        119069.discord  (04/20/2021 05:19:44 PM)        (Detached)
1 Socket in /run/screen/S-miyavi.

**Comment by murkyl** [comment]
Masaya, the start.sh: 47: pushd: not found and the popd: not found are new additions. I had suggested them to the maintainer but it looks like those commands are not present on your machine. That is very strange for a Linux box. What distribution are you using? Those 2 errors are meant to save the current working directory and then 'cd' into the backups directory. Then it will clean out the old backups before changing the current working directory back to wherever you ran the script from.

**Comment by MasayaKondo999** [comment]
I'm using Ubuntu 20.04.2

**Comment by MasayaKondo999** [comment]
I tryed delete "minecraftbe" directory ,and re-install . but it happened same dialog (start.sh 47 ) .

**Comment by MasayaKondo999** [comment]
miyavi@miyaviserver:~$ sh SetupMinecraft.sh
Minecraft Bedrock Server installation script by James Chambers
Latest version always at https://github.com/TheRemote/MinecraftBedrockServer
Don't forget to set up port forwarding on your router!  The default port is 19132
SetupMinecraft.sh: 17: function: not found
SetupMinecraft.sh: 22: Bad substitution
miyavi@miyaviserver:~$

**Comment by MasayaKondo999** [comment]
I am so sorry , it was just small problem .
I use start.sh with "sh" , not "bash" . 
I tryed "bash start.sh" . it worked completely .

Thank you
