### ISSUE TITLE
crontab reboot

### ISSUE THREAD

**Issue by stxdigitizing** [TheRemote/MinecraftBedrockServer#85]
I've noticed that my crontab is set to reboot at 4 am but it reboots at 11pm. What would be causing this issue? 

current settings 0 4 * * *  /Path to restart.sh

**Comment by albertoberreteaga** [comment]
Did you check your user crontab, with "crontab -e" and root contrab, with "sudo crontab -e"? Perhaps you have 2 different configs on 2 different users?

**Comment by murkyl** [comment]
You can run:
`timedatectl`
and also
`sudo timedatectl`

You should be logged in as that regular user that you are using to launch the Minecraft server when you run the command. This will give you the time zone information for your account. If you run this as root (sudo) then it will show you the time zone for the system. When you use crontab -e you are using the crontab for a single user.

**Comment by stxdigitizing** [comment]
i checked both and they are both identical.
`@minecraftrm:~$ timedatectl
                      Local time: Thu 2021-05-13 20:43:44 CDT
                  Universal time: Fri 2021-05-14 01:43:44 UTC
                        RTC time: Fri 2021-05-14 01:43:45
                       Time zone: US/Central (CDT, -0500)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
@minecraftrm:~$ sudo timedatectl
                      Local time: Thu 2021-05-13 20:43:52 CDT
                  Universal time: Fri 2021-05-14 01:43:52 UTC
                        RTC time: Fri 2021-05-14 01:43:53
                       Time zone: US/Central (CDT, -0500)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
`

crontab is being used with the regular user account.

**Comment by murkyl** [comment]
What distribution are you using? There are lots of slight differences across the different cron daemons and distributions.

**Comment by stxdigitizing** [comment]
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

**Comment by TheRemote** [comment]
Hello,

On some distributions it seems to always go by UTC.  I'm not totally sure why but you can realign the time to match.  It's annoying and if anyone knows a fix let me know!
