### ISSUE TITLE
Please Help Me Understand.

### ISSUE THREAD

**Issue by HughSparks** [TheRemote/MinecraftBedrockServer#9]
The install seems pretty straight forward and It seems like it is well built. (as far as i can tell -\(~.~)/- ). I set up my system a while ago. It uses the most basic crontab + screen combo possible to launch my server automatically. (I'm proud of it but i want to improve.) I have herd about systemd but cant figure out how to use it and I want to learn enough to write an auto update similar to what you have. If you can, will you explain in as much detail as you can how lines 37 to the end of start.sh works.

I know this isn't an issue but i didn't know how to ask you otherwise.

Hugh Sparks
(The 15yo wannabe programmer)

**Comment by TheRemote** [comment]
Here is a good place to start with systemd:

https://www.freedesktop.org/software/systemd/man/systemd.service.html
