### ISSUE TITLE
Does this work on Fedora

### ISSUE THREAD

**Issue by TangledWiresYT** [TheRemote/MinecraftBedrockServer#90]
Personally I use Fedora Linux instead of Debian so I was wondering whether this would work.

**Comment by TheRemote** [comment]
It should work!  The only issue you may run into is it will try to use apt to install a few basic requirements.  

These will probably already be on your system and if not they are easy to find replacements for (it's things like wget, curl, etc).

We used to run into $PATH variable issue but it now stores those in the script so it should definitely work!

**Comment by TangledWiresYT** [comment]
Ok thank you!
