### ISSUE TITLE
Folders created in wrong directory

### ISSUE THREAD

**Issue by CobraBitYou** [TheRemote/MinecraftBedrockServer#93]
At the beginning of the `start.sh` script, the if statements check for if the logs, downloads, and backups folders exist. If they don't exist, it creates them. I noticed that the script decides to save the folders in the home directory (one folder above the `minecraftbe` folder). Maybe add something like the following:

```
path="/home/$USER/minecraftbe" #<-- this is new
if [ ! -d "logs" ]; then
mkdir $path/logs #<-- add the $path variable so it makes it in the right directory
fi

#Then do the same thing for each of the other folders
```

You could also do this before checking for if the directories exist:

```
cd /home/$USER/minecraftbe

if [ ! -d "logs" ]; then
mkdir logs
fi

#This method is so much simpler (make sure to cd back to home afterwards though

cd ~
```

**Comment by da99Beast** [comment]
I would like to point out that some of us may install to a path outside of the /home structure so hard coding to that would be bad.  With the setup we specified the install path (mine was /opt) so we should have a record of where the Minecraft is installed to and where the start/stop/restart files are and where the logs/downloads/backups folders should be.

Just looked, line 45-46 (comment and cd commands) we switch to the proper folder.  We should probably move the checks for the logs/downloads/backups folder to after this or move lines 45-46 above the folder check to resolve properly.

**Comment by CobraBitYou** [comment]
> I would like to point out that some of us may install to a path outside of the /home structure so hard coding to that would be bad. With the setup we specified the install path (mine was /opt) so we should have a record of where the Minecraft is installed to and where the start/stop/restart files are and where the logs/downloads/backups folders should be.
> 
> Just looked, line 45-46 (comment and cd commands) we switch to the proper folder. We should probably move the checks for the logs/downloads/backups folder to after this or move lines 45-46 above the folder check to resolve properly.

True! I’ve always installed it to my home directory for convenience. I suppose that it would be easier to ask the user for a specific path in the setup script then save the variable to a file (then import with the source command). I was working on some scripts to account for variables but it’s going to take a while with my busy schedule.

**Comment by starkey-01** [comment]
@CobraBitYou are you running this as a service or manually executing start.sh when you need to?

The logs, downloads and backups folder are inside the server name folder for me. I believe the reason for that is the service runs start.sh from inside the server folder.

Noting that I am installing to a custom directory outside of the home directory too. 

```
minecraftbe/
└── servername
    ├── backups
    ├── behavior_packs
    ├── definitions
    ├── development_behavior_packs
    ├── development_resource_packs
    ├── development_skin_packs
    ├── downloads
    ├── logs
    ├── minecraftpe
    ├── premium_cache
    ├── resource_packs
    ├── structures
    ├── treatments
    ├── world_templates
    └── worlds
```

**Comment by CobraBitYou** [comment]
> @CobraBitYou are you running this as a service or manually executing start.sh when you need to?
> 
> The logs, downloads and backups folder are inside the server name folder for me. I believe the reason for that is the service runs start.sh from inside the server folder.
> 
> Noting that I am installing to a custom directory outside of the home directory too.
> 
> ```
> minecraftbe/
> └── servername
>     ├── backups
>     ├── behavior_packs
>     ├── definitions
>     ├── development_behavior_packs
>     ├── development_resource_packs
>     ├── development_skin_packs
>     ├── downloads
>     ├── logs
>     ├── minecraftpe
>     ├── premium_cache
>     ├── resource_packs
>     ├── structures
>     ├── treatments
>     ├── world_templates
>     └── worlds
> ```

I usually run it with `sudo systemctl start mcpe`. The folders on my device also show up within the minecraftbe/$servername directory (probably from the original setup). However, when I delete the folders in my home directory, they reappear after I restart my server. 

So, it sounds like you use `start.sh` to start the server and it creates the folders in the right directory. I assume it has something to do with the permissions and method of executing `start.sh`.

For example, I have a `reboot.sh` script that starts the server at reboot, schedules a shutdown and startup (which loops it continuously for an entire week), and tells the Minecraft server to stop at a specific time. It starts this script at reboot through the sudo crontab. Maybe running using sudo is causing the issue?

**Comment by TheRemote** [comment]
It sounds like you may have a mix of using an old SetupMinecraft.sh (it has been changing almost every week) that is downloading newer versions of start.sh from the repository.

The new version of the scripts you choose where to install it (~ is the default, and how the old script always used to work until very recently).  This sounds like it may be a case of mixing and matching SetupMinecraft.sh and the latest repository scripts.

I've actually changed my recommended way of running the script to:

`curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh | bash`

This way doesn't save any copy of SetupMinecraft.sh at all since that has caused nothing but trouble.  Can you verify all this and try with the latest version and see if this behavior is gone?
