### ISSUE TITLE
missing version to dowload

### ISSUE THREAD

**Issue by buczoprazy** [TheRemote/MinecraftBedrockServer#99]
Hi,

Missing version to download.

Thanks

**Comment by TheRemote** [comment]
I'm not sure what this means to be honest.  I don't control the Minecraft versions.

**Comment by buczoprazy** [comment]
There is a version but on other file:
` RaspberryPiMinecraft/SetupMinecraft.sh `

`# Minecraft server version
Version="1.17.1"`

**Comment by TheRemote** [comment]
What is the question?  The scripts are templates.  Everything is replaced by SetupMinecraft.sh with what you put in there.

If you want to change the version from there you can change it to whatever you want!
